### PR TITLE
Function generator

### PR DESCRIPTION
**Pull request by townsnic**
Remote access driver for the VSG, capable of setting the frequency, phase, and amplitude of the output, performing sweeps, and other minor functionalities.

### CODE REVIEW

**Comment by sequoiap** [comment]
@townsnic Is this branch ready for merging? I made some significant structural changes to the master branch, so if it's ready, I'll rework this slightly for the merge, but if you're still working on it I'll wait until you give the green light

**Comment by townsnic** [comment]
> @townsnic Is this branch ready for merging? I made some significant structural changes to the master branch, so if it's ready, I'll rework this slightly for the merge, but if you're still working on it I'll wait until you give the green light

**Comment by townsnic** [comment]
@sequoiap Yes it's ready

**Comment by sequoiap** [comment]
@townsnic A couple notes, just for your future reference and helping you become an even more "Pythonic" programmer:

* Class name capitalization should be CamelCase, not snake_case. So, ``Function_Generator`` becomes ``FunctionGenerator``.
* You should not really have imports at the top that never get used, so removing ``import time``.
* Wildcard imports ``from package import *`` are general frowned upon, it's better to explicitly say what you're importing or to use the namespace ``import package; package.some_function()``. It helps with code maintenance; if you import ``*``, I can't tell which functions came from which module, or if the module even needs to be there.

I've fixed the above things. But, one clarifying question--why do you have ``from pyrolab import __version__``? Are you using the version string somewhere?

**Comment by sequoiap** [comment]
Also, you should install pylint into vscode, it'll help catch some errors. For example, type hinting "string" but assigning it None is invalid, proper way is to assign it as ``Optional[str]``.m

Pylint caught this one error: cannot assign float to int. This is in ``freq_step_up`` and ``freq_step_down`` where ``1e6`` is a float, but you say you require an int. The command string you build--does it need to be an int, or can it be a float? If it needs to be an int, you'll want to cast it to an int explicitly, or we might be sending weird malformed strings over to the function generator. Can you verify for me?

**Comment by townsnic** [comment]
@sequoiap Honestly, I'm not sure about the imports. I duplicated most of what was present in the SMU and scope drivers and was working with Christian trying to import the VISAResourceExtension file. For whatever reason it was being really tricky and wasn't finding it which is why we used the wildcard import. 
As far as an int vs float, it can be either. That was just an error on my part. 
Thanks!

**Pull request merged**
